import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import SideFabContact from "../components/SideFabContact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}>
        {/* LOGO Header（每頁自動套用，並可點擊回首頁） */}
        <header className="bg-white py-4 shadow flex justify-center mb-2">
          <Link href="/" className="block">
            <img
              src="/showall logo.png"
              alt="SHOWALL LOGO"
              className="mx-auto h-16 object-contain"
              draggable={false}
              style={{ cursor: "pointer" }}
            />
          </Link>
        </header>
        {/* 主內容（各頁內容） */}
        {children}
        <SideFabContact />
      </body>
    </html>
  );
}
